name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # or master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main  # or master

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4

      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"              # root directory where index.html is located
          skip_app_build: true           # skip Oryx build since this is a static HTML site
          output_location: "/"           # output directory (same as input)
          skip_deploy_on_missing_secrets: true  # safely skip deploy if token is missing
